print('---------------')
print('  Desafio 04')
print('---------------')
print('')
var = input('Digite algo:')
print('')
print('O que foi digitado pode ser um número?',var.isnumeric())
print('Pode ser alphabético?',var.isalpha())
print('Pode ser um número decimal?',var.isdecimal())
print('O que foi digitado está escrito em minúsculas?',var.islower())
print('O que foi digitado está escrito em maiúsculas?',var.isupper())
print('O que foi digitado é um espaço?',var.isspace())
print('Pode ser um alpha numérico?',var.isnumeric())
print('Está capitalizada?',var.istitle())
