print('------ Desafio 02 ------')
nome = input('Informe seu nome:')
dia = input('Informe o dia do seu nascimento:')
mes = input('Informe o mês do seu nascimento:')
ano = input('Informe o ano do seu nascimento:')
print(nome, 'sua data de nascimento é: ',dia,'/',mes,'/',ano)